# CMake generated Testfile for 
# Source directory: /users/jeaohlee/desktop/cmpt373/se-background-template/test
# Build directory: /Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[unit01]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit01")
set_tests_properties([=[unit01]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;52;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit02]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit02")
set_tests_properties([=[unit02]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;53;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit03]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit03")
set_tests_properties([=[unit03]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;54;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit04]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit04")
set_tests_properties([=[unit04]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;55;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit05]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit05")
set_tests_properties([=[unit05]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;56;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit06]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit06")
set_tests_properties([=[unit06]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;57;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit07]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit07")
set_tests_properties([=[unit07]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;58;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
add_test([=[unit08]=] "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin/unit08")
set_tests_properties([=[unit08]=] PROPERTIES  WORKING_DIRECTORY "/Users/jeaohlee/Desktop/CMPT373/se-background-template/se-background-build/bin" _BACKTRACE_TRIPLES "/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;46;add_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;59;compile_unit_test;/users/jeaohlee/desktop/cmpt373/se-background-template/test/CMakeLists.txt;0;")
